# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - conversion: onnx.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

checkpoint_path: checkpoints/distilroberta-base.ckpt
sequence_length: 65

hydra:
  output_subdir: null
  run:
    dir: .

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}
