# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - datamodule: sst_datamodule.yaml
  - backend: torch.yaml

  # Stop hydra from cluttering repo
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

checkpoint_path: checkpoints/distilroberta-base.ckpt
device: cuda

# Stop hydra from cluttering repo
hydra:
  output_subdir: null
  run:
    dir: .

# Logger info. Lightning loggers are not used for benchmarking bc using
# Lightning trainer to run the prediction is too restrictive
# Only wandb is supported here
wandb:
  project: "sst"
  name: null
  job_type: "benchmark"
  group: ""
  tags: []

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}
