# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_demo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: get_revision
        run: export LATEST_REVISION=`git rev-parse HEAD`
          
      - name: update_huggingface_requirements
        env:
          HUGGINGFACE_PW: ${{ secrets.HUGGINGFACE_PW }}
        run: |
          cd ..
          python3 -c 'import os; pw = os.environ["HUGGINGFACE_PW"]; os.system(f"git clone https://ArsenieBoca:{pw}@huggingface.co/spaces/ArsenieBoca/EfficientSentimentAnalysis")'
          cd EfficientSentimentAnalysis
          python3 -c 'import os; r = open("requirements.txt").read(); base = r[:r.rfind("@")+1]; open("requirements.txt", "w").write(base + os.environ["LATEST_REVISION"])'
          git add requirements.txt
          git commit -m "update pip revision"
          git push
          cd $GITHUB_WORKSPACE
          
      
        
        
      
        
